# Generated by Django 4.0.3 on 2022-04-17 08:35

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbookz', '0002_alter_contactlist_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='contact_address',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=1000), default=list, size=None),
        ),
    ]
