# Generated by Django 4.0.3 on 2022-04-17 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addbookz', '0003_alter_contactlist_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactlist',
            name='contact_address',
            field=models.CharField(max_length=1000),
        ),
    ]
